version: "3.3"
services:
  postgres:
    image: kvezal/cities-postgres:latest
    container_name: postgres
    env_file: environments/postgres.env
    networks:
      - six-cities
    stdin_open: true
    tty: true
  api:
    image: kvezal/cities-api:latest
    container_name: api
    env_file: environments/api.env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    networks:
      - six-cities
    entrypoint: /app/scripts/api.sh fake
    stdin_open: true
    tty: true
networks:
  six-cities:
